name: msft
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  flutter_native_splash: ^2.3.1
  flutter_launcher_icons: ^0.13.1
  sizer: ^2.0.15
  carousel_slider: ^4.2.1
  flutter_rating_bar: ^4.0.1

  # state management
  provider: ^6.0.5

  # firebase packages
  firebase_auth: ^4.6.3
  firebase_core: ^2.14.0
  cloud_firestore: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter_native_splash:
  color: "#ffffff"
  image: assets/images/app/black_logo.png
  color_dark: "#000000"
  image_dark: assets/images/app/white_logo.png

  android_12:
    image: assets/images/app/black_logo.png
    icon_background_color: "#ffffff"
    image_dark: assets/images/app/white_logo.png
    icon_background_color_dark: "#000000"

  web: false

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app/MSFT.png"
  min_sdk_android: 21

flutter:

  uses-material-design: true

  assets: 
    - assets/images/app/
    - assets/images/bank/
    - assets/icons/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
        - asset: assets/fonts/poppins/Poppins-ExtraBoldItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/poppins/Poppins-ExtraBold.ttf
          weight: 900
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
          weight: 500
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
          weight: 300
